name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : récupérer le code du dépôt
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # clone complet pour PR

      # Étape 2 : configurer python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests and generate coverage
        run: |
          pytest --cov=Houblon --cov-report=xml
      # Étape 3 : mettre en cache les fichiers Sonar pour accélérer
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # Étape 4 : lancer l'analyse SonarCloud
      - name: SonarCloud / SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@aa494459d7c39c106cc77b166de8b4250a32bb97
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
             -Dsonar.projectKey=DimitriGerson_Houblon
             -Dsonar.organization=dimitrigerson
             -Dsonar.host.url=https://sonarcloud.io
             -Dsonar.sources=src
             -Dsonar.tests=test
             -Dsonar.python.coverage.reportPaths=coverage.xml
             -Dproject.settings=./sonar-project.properties
             -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} 
             -Dsonar.pullrequest.branch=${{ github.head_ref }} 
             -Dsonar.pullrequest.base=${{ github.base_ref }} 
             -Dsonar.analysis.mode=publish
